title:  The Primary Brain
tagline: Resources for Primary Teachers
store: https://www.teacherspayteachers.com/store/the-primary-brain
author:
  name: 'Laurin Brainard'
  twitter:  theprimarybrain

# Default FloDesk Form ID:
flodeskDefault: 5d7d97fb1093300012a8c764

# Change to true for Disqus comments
#disqus:
#  comments: false
#  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-107720904-1'

menu:
- {
    name: 'About', 
    url: 'about/'
  }
- {
    name: 'Blog', 
    url: 'blog/'
  }
- {
    name: 'Contact',
    url: 'contact/'
  }
- {
    name: 'My Book',
    url: 'book/'
  }
- {
    name: 'Categories', 
    url: 'categories/'
  }
- {
    name: 'Newsletter', 
    url: 'newsletter/'
  }

social:
#- {icon: 'github', link: 'https://www.github.com/lenpaul'}
#- {icon: 'twitter', link: 'https://twitter.com/paululele'}
#- {icon: 'linkedin', link: 'http://www.linkedin.com/in/lenpaul/'}
- {icon: 'instagram', link: 'https://instagram.com/theprimarybrain'}
- {icon: 'pinterest', link: 'https://www.pinterest.com/theprimarybrain'}
- {icon: 'facebook', link: 'https://www.facebook.com/theprimarybrain'}
#- {icon: 'envelope', link: 'mailto:theprimarybrain@gmail.com'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer

facebook_app_id: 299117043903722
